name = "Tries"
uuid = "666c268a-d78f-417b-b45a-09e10b365109"
authors = ["Gregor Kappler"]
version = "0.1.1"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"

[compat]
AbstractTrees = "0.2.1, 0.3.3"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
